version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: chatty-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chatty
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - chatty-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatty-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/chatty?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: "604800"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - chatty-network
    volumes:
      - ./backend/src:/app/src:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatty-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatty-network

# Named volumes for data persistence
volumes:
  mongodb_data:
    driver: local

# Custom network for service communication
networks:
  chatty-network:
    driver: bridge
